image: Visual Studio 2017 RC
version: '0.1.0.{build}'
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- nuget install Cake -ExcludeVersion
build_script:
- .\Cake\Cake.exe --target=Build --packageVersion=%APPVEYOR_BUILD_VERSION% --currentBranch=%APPVEYOR_REPO_BRANCH%
after_build:
- .\Cake\Cake.exe --target=Pack --packageVersion=%APPVEYOR_BUILD_VERSION% --currentBranch=%APPVEYOR_REPO_BRANCH%
test_script:
- .\Cake\Cake.exe --target=UnitTest
deploy:
  provider: NuGet
  server: https://www.myget.org/F/protoactor/api/v2/package
  api_key:
    secure: EsuJKJ3FzjcSX1xp9nKr0Lg+xVkIg5EGYB1FEuwIE/dm0lFolL7LKd3G3F6Z195+
  skip_symbols: false
  symbol_server: https://www.myget.org/F/protoactor/symbols/api/v2/package
artifacts:
- path: out\*
