name: Build and test PRs

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: '6'          
      - uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: '4.2'                  

      - name: Build
        run: dotnet build -c Release

      - name: Run tests netcoreapp3.1
        run: |
          dotnet test -c Release --framework netcoreapp3.1

      - name: Run tests net5.0
        run: |
          dotnet test -c Release --framework net5.0
