name: Build and test PRs

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.102'
          
      - name: Run tests netcoreapp3.1
        run: |
          dotnet build -c Release
          dotnet test --no-build
