name: Build and test PRs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'               

      - name: Build
        run: |
          dotnet build -c Release
          
      - name: Run tests netcoreapp3.1
        env:
          ConnectionStrings__MongoDB: mongodb://127.0.0.1:${{ job.services.mongodb.ports[27017] }}/ProtoMongo
          ConnectionStrings__Redis: localhost:${{ job.services.redis.ports[6379] }}
        run: |
          dotnet test -c Release --framework netcoreapp3.1
          
      - name: Run tests net5.0
        env:
          ConnectionStrings__MongoDB: mongodb://127.0.0.1:${{ job.services.mongodb.ports[27017] }}/ProtoMongo
          ConnectionStrings__Redis: localhost:${{ job.services.redis.ports[6379] }}
        run: |
            dotnet test -c Release --framework net5.0