name: Build and test PRs

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: '6'          
      - uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: '4.2'                  

      - name: Build
        run: dotnet build -c Release

      - name: Run tests netcoreapp3.1
        env:
          ConnectionStrings__MongoDB: mongodb://localhost:${{ job.services.mongodb.ports[27017] }}/ProtoMongo
          ConnectionStrings__Redis: localhost:${{ job.services.redis.ports[6379] }}
        run: |
          dotnet test -c Release --framework netcoreapp3.1

      - name: Run tests net5.0
        env:
          ConnectionStrings__MongoDB: mongodb://localhost:${{ job.services.mongodb.ports[27017] }}/ProtoMongo
          ConnectionStrings__Redis: localhost:${{ job.services.redis.ports[6379] }}
        run: |
          dotnet test -c Release --framework net5.0
